/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Gui;

import GuiFormularios.frmBeca;
import GuiFormularios.frmConsolidado;
import GuiFormularios.frmCoordinador;
import GuiFormularios.frmDeuda;
import GuiFormularios.frmEstadoCuenta;
import GuiFormularios.frmLogin;
import GuiFormularios.frmRegistroComprobante;
import GuiFormularios.frmRegistroMaestrante;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tania Silva
 */
public class frmFormularios extends javax.swing.JFrame implements Runnable {

    String hora,minutos,segundos,ampm;
    Calendar calendario;
    Thread h1;
    /**
     * Creates new form frmFormularios
     */
    public frmFormularios() {
        initComponents();
        
        frmLogin ec= new frmLogin();       
        jCallerImage.add(ec);
        ec.setVisible(true);
        ec.setLocation(350, 100);
        jPanel4.setVisible(false);
        
        h1 = new Thread(this);
        h1.start();
        jfecha1.setText(fecha());
        setLocationRelativeTo(null);
        setTitle("SICOP");
        setVisible(true);
        this.setExtendedState(frmFormularios.MAXIMIZED_BOTH);
    }


    @Override
    public void run() {
       Thread ct = Thread.currentThread();
       while(ct==h1){
           calcula();
           jtime.setText(hora+":"+minutos+":"+segundos+""+ampm);
           try{
              Thread.sleep(1000);
           }catch (InterruptedException e){
               
           }
       }
    }
    
    
    private void calcula() {
     Calendar Calendario = new GregorianCalendar();
     Date fechaHoraActual = new Date();
     
     Calendario.setTime(fechaHoraActual);
     ampm = Calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
     
        if (ampm.equals("PM")) {
            int h = Calendario.get(Calendar.HOUR_OF_DAY)-12;
            hora = h>9?""+h:"0"+h;
        }else   
        {
            hora = Calendario.get(Calendar.HOUR_OF_DAY)>9?""+Calendario.get(Calendar.HOUR_OF_DAY):"0"+Calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = Calendario.get(Calendar.MINUTE)>9?""+Calendario.get(Calendar.MINUTE):"0"+Calendario.get(Calendar.MINUTE);
        segundos = Calendario.get(Calendar.SECOND)>9?""+Calendario.get(Calendar.SECOND):"0"+Calendario.get(Calendar.SECOND); 
    } 

    public static  String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd-MMMM-yyyy");
        return formatofecha.format(fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jMenu1 = new javax.swing.JMenu();
        jLbPrincipalPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jtime = new javax.swing.JLabel();
        jLblUser = new javax.swing.JLabel();
        jfecha1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBtnmaximizar = new javax.swing.JButton();
        jBtnminimizar = new javax.swing.JButton();
        jLblMaes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCallerImage = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jBtnPagos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnConfiguracion = new javax.swing.JButton();
        jBtnMaestrante = new javax.swing.JButton();
        jBtnCoordinador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnBecas = new javax.swing.JButton();
        jBtnDeuda = new javax.swing.JButton();
        jBtnConsolidado = new javax.swing.JButton();
        jBtnEstadoCuenta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jRadioButton1.setText("jRadioButton1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SICOP");
        setBackground(new java.awt.Color(255, 204, 0));
        setUndecorated(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });

        jLbPrincipalPanel.setBackground(new java.awt.Color(204, 204, 204));
        jLbPrincipalPanel.setMaximumSize(new java.awt.Dimension(850, 500));
        jLbPrincipalPanel.setMinimumSize(new java.awt.Dimension(850, 500));

        jPanel3.setBackground(new java.awt.Color(0, 51, 90));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("S.I.C.O.P");

        jButton3.setBackground(new java.awt.Color(0, 50, 91));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/login.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jtime.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jtime.setForeground(new java.awt.Color(255, 255, 255));
        jtime.setText("Reloj");

        jLblUser.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLblUser.setForeground(new java.awt.Color(255, 255, 255));
        jLblUser.setText("User");

        jfecha1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jfecha1.setForeground(new java.awt.Color(255, 255, 255));
        jfecha1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jfecha1.setText("Fecha");

        jButton1.setBackground(new java.awt.Color(0, 51, 90));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cerrar-ventana (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtnmaximizar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnmaximizar.setForeground(new java.awt.Color(255, 204, 0));
        jBtnmaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/compartir-flecha.png"))); // NOI18N
        jBtnmaximizar.setBorder(null);
        jBtnmaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnmaximizarMouseClicked(evt);
            }
        });
        jBtnmaximizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnmaximizarActionPerformed(evt);
            }
        });

        jBtnminimizar.setBackground(new java.awt.Color(0, 52, 90));
        jBtnminimizar.setForeground(new java.awt.Color(255, 204, 0));
        jBtnminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/minimizar.png"))); // NOI18N
        jBtnminimizar.setBorder(null);
        jBtnminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnminimizarMouseClicked(evt);
            }
        });
        jBtnminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnminimizarActionPerformed(evt);
            }
        });

        jLblMaes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLblMaes.setForeground(new java.awt.Color(255, 255, 255));
        jLblMaes.setText("Tipo");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/LogoAplicación (2).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Control de Pagos de Postgrado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(152, 152, 152)
                        .addComponent(jfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtime, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLblMaes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnmaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfecha1)
                    .addComponent(jtime)
                    .addComponent(jLblMaes)
                    .addComponent(jLblUser)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnminimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnmaximizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jCallerImage.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jCallerImageLayout = new javax.swing.GroupLayout(jCallerImage);
        jCallerImage.setLayout(jCallerImageLayout);
        jCallerImageLayout.setHorizontalGroup(
            jCallerImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jCallerImageLayout.setVerticalGroup(
            jCallerImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 90));

        jBtnPagos.setBackground(new java.awt.Color(0, 51, 90));
        jBtnPagos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnPagos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/bills.png"))); // NOI18N
        jBtnPagos.setText("Pagos                  ");
        jBtnPagos.setBorder(null);
        jBtnPagos.setContentAreaFilled(false);
        jBtnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPagos.setOpaque(true);
        jBtnPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnPagosMouseExited(evt);
            }
        });
        jBtnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPagosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Menú");

        jBtnConfiguracion.setBackground(new java.awt.Color(0, 51, 90));
        jBtnConfiguracion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/informacion.png"))); // NOI18N
        jBtnConfiguracion.setText("Información        ");
        jBtnConfiguracion.setBorder(null);
        jBtnConfiguracion.setContentAreaFilled(false);
        jBtnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnConfiguracion.setOpaque(true);
        jBtnConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnConfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnConfiguracionMouseExited(evt);
            }
        });
        jBtnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfiguracionActionPerformed(evt);
            }
        });

        jBtnMaestrante.setBackground(new java.awt.Color(0, 51, 90));
        jBtnMaestrante.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnMaestrante.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMaestrante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/maestro.png"))); // NOI18N
        jBtnMaestrante.setText("Maestrante          ");
        jBtnMaestrante.setBorder(null);
        jBtnMaestrante.setContentAreaFilled(false);
        jBtnMaestrante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnMaestrante.setOpaque(true);
        jBtnMaestrante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnMaestranteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnMaestranteMouseExited(evt);
            }
        });
        jBtnMaestrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMaestranteActionPerformed(evt);
            }
        });

        jBtnCoordinador.setBackground(new java.awt.Color(0, 51, 90));
        jBtnCoordinador.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnCoordinador.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCoordinador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/coordinador.png"))); // NOI18N
        jBtnCoordinador.setText("Coordinador         ");
        jBtnCoordinador.setBorder(null);
        jBtnCoordinador.setContentAreaFilled(false);
        jBtnCoordinador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCoordinador.setOpaque(true);
        jBtnCoordinador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnCoordinadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnCoordinadorMouseExited(evt);
            }
        });
        jBtnCoordinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCoordinadorActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/menu-desplegable.png"))); // NOI18N

        jBtnBecas.setBackground(new java.awt.Color(0, 51, 90));
        jBtnBecas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnBecas.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/beca.png"))); // NOI18N
        jBtnBecas.setText("Becas                     ");
        jBtnBecas.setBorder(null);
        jBtnBecas.setContentAreaFilled(false);
        jBtnBecas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnBecas.setOpaque(true);
        jBtnBecas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBecasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBecasMouseExited(evt);
            }
        });
        jBtnBecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBecasActionPerformed(evt);
            }
        });

        jBtnDeuda.setBackground(new java.awt.Color(0, 51, 90));
        jBtnDeuda.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnDeuda.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDeuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/deuda.png"))); // NOI18N
        jBtnDeuda.setText("  Deuda                 ");
        jBtnDeuda.setBorder(null);
        jBtnDeuda.setContentAreaFilled(false);
        jBtnDeuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnDeuda.setOpaque(true);
        jBtnDeuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDeudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDeudaMouseExited(evt);
            }
        });
        jBtnDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeudaActionPerformed(evt);
            }
        });

        jBtnConsolidado.setBackground(new java.awt.Color(0, 51, 90));
        jBtnConsolidado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnConsolidado.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConsolidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/script.png"))); // NOI18N
        jBtnConsolidado.setText("Consolidado        ");
        jBtnConsolidado.setBorder(null);
        jBtnConsolidado.setContentAreaFilled(false);
        jBtnConsolidado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnConsolidado.setOpaque(true);
        jBtnConsolidado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnConsolidadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnConsolidadoMouseExited(evt);
            }
        });
        jBtnConsolidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsolidadoActionPerformed(evt);
            }
        });

        jBtnEstadoCuenta.setBackground(new java.awt.Color(0, 51, 90));
        jBtnEstadoCuenta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jBtnEstadoCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEstadoCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/estado de cuenta.png"))); // NOI18N
        jBtnEstadoCuenta.setText("Estado de Cuenta");
        jBtnEstadoCuenta.setBorder(null);
        jBtnEstadoCuenta.setContentAreaFilled(false);
        jBtnEstadoCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnEstadoCuenta.setOpaque(true);
        jBtnEstadoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEstadoCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEstadoCuentaMouseExited(evt);
            }
        });
        jBtnEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEstadoCuentaActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/work-from-home (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBecas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnDeuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnMaestrante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnEstadoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConsolidado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jBtnEstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMaestrante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnBecas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jBtnDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCoordinador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConsolidado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLbPrincipalPanelLayout = new javax.swing.GroupLayout(jLbPrincipalPanel);
        jLbPrincipalPanel.setLayout(jLbPrincipalPanelLayout);
        jLbPrincipalPanelLayout.setHorizontalGroup(
            jLbPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jLbPrincipalPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCallerImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLbPrincipalPanelLayout.setVerticalGroup(
            jLbPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jLbPrincipalPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLbPrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCallerImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbPrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbPrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPagosActionPerformed
        // TODO add your handling code here:
       
         jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmRegistroComprobante obb = new frmRegistroComprobante();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setLocation(350, 100);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnPagosActionPerformed

    private void jBtnPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPagosMouseEntered
        // TODO add your handling code here:
         jBtnPagos.setBackground(Color.white);
         jBtnPagos.setForeground(Color.black);
    }//GEN-LAST:event_jBtnPagosMouseEntered

    private void jBtnPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPagosMouseExited
        jBtnPagos.setBackground(new Color(0,51,90));
        jBtnPagos.setForeground(Color.white);
    }//GEN-LAST:event_jBtnPagosMouseExited

    private void jBtnConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConfiguracionMouseEntered
        // TODO add your handling code here:
        jBtnConfiguracion.setBackground(Color.white);
        jBtnConfiguracion.setForeground(Color.black);
    }//GEN-LAST:event_jBtnConfiguracionMouseEntered

    private void jBtnConfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConfiguracionMouseExited
       jBtnConfiguracion.setBackground(new Color(0,51,90));
       jBtnConfiguracion.setForeground(Color.white);
    }//GEN-LAST:event_jBtnConfiguracionMouseExited

    private void jBtnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfiguracionActionPerformed

         jCallerImage.removeAll();
        jCallerImage.repaint();
        frmInfo ec= new frmInfo();
        jCallerImage.add(ec);
        ec.show();
        ec.setLocation(350, 100);
    }//GEN-LAST:event_jBtnConfiguracionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jCallerImage.removeAll();
        jCallerImage.repaint();
        frmLogin ec= new frmLogin();
        jCallerImage.add(ec);
        ec.show();
        ec.setLocation(280, 100);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtnMaestranteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMaestranteMouseEntered
        // TODO add your handling code here:
         jBtnMaestrante.setBackground(Color.white);
         jBtnMaestrante.setForeground(Color.black);
    }//GEN-LAST:event_jBtnMaestranteMouseEntered

    private void jBtnMaestranteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnMaestranteMouseExited
        // TODO add your handling code here:
        jBtnMaestrante.setBackground(new Color(0,51,90));
        jBtnMaestrante.setForeground(Color.white);
    }//GEN-LAST:event_jBtnMaestranteMouseExited

    private void jBtnMaestranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMaestranteActionPerformed
        // TODO add your handling code here:
        jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmRegistroMaestrante obb = new frmRegistroMaestrante();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnMaestranteActionPerformed

    private void jBtnCoordinadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCoordinadorMouseEntered
        // TODO add your handling code here:
        jBtnCoordinador.setBackground(Color.white);
        jBtnCoordinador.setForeground(Color.black);
    }//GEN-LAST:event_jBtnCoordinadorMouseEntered

    private void jBtnCoordinadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCoordinadorMouseExited
        // TODO add your handling code here:
         jBtnCoordinador.setBackground(new Color(0,51,90));
         jBtnCoordinador.setForeground(Color.white);
    }//GEN-LAST:event_jBtnCoordinadorMouseExited

    private void jBtnCoordinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCoordinadorActionPerformed
        // TODO add your handling code here:
        jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmCoordinador obb = new frmCoordinador();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnCoordinadorActionPerformed

    private void jBtnBecasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBecasMouseEntered
        // TODO add your handling code here:
        jBtnBecas.setBackground(Color.white);
        jBtnBecas.setForeground(Color.black);
    }//GEN-LAST:event_jBtnBecasMouseEntered

    private void jBtnBecasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBecasMouseExited
        // TODO add your handling code here:
        jBtnBecas.setBackground(new Color(0,51,90));
        jBtnBecas.setForeground(Color.white);
    }//GEN-LAST:event_jBtnBecasMouseExited

    private void jBtnBecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBecasActionPerformed
       
        jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmBeca obb = new frmBeca();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnBecasActionPerformed

    private void jBtnDeudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDeudaMouseEntered
        jBtnDeuda.setBackground(Color.white);
        jBtnDeuda.setForeground(Color.black);
    }//GEN-LAST:event_jBtnDeudaMouseEntered

    private void jBtnDeudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDeudaMouseExited
         jBtnDeuda.setBackground(new Color(0,51,90));
         jBtnDeuda.setForeground(Color.white);
    }//GEN-LAST:event_jBtnDeudaMouseExited

    private void jBtnDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeudaActionPerformed
       
        jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmDeuda obb = new frmDeuda();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnDeudaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnmaximizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnmaximizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jBtnmaximizarActionPerformed

    private void jBtnmaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnmaximizarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnmaximizarMouseClicked

    private void jBtnminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnminimizarActionPerformed
        // TODO add your handling code here:
      this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jBtnminimizarActionPerformed

    private void jBtnminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnminimizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnminimizarMouseClicked

    private void jBtnConsolidadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsolidadoMouseEntered
        // TODO add your handling code here:
        jBtnConsolidado.setBackground(Color.white);
        jBtnConsolidado.setForeground(Color.black);
    }//GEN-LAST:event_jBtnConsolidadoMouseEntered

    private void jBtnConsolidadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConsolidadoMouseExited
        // TODO add your handling code here:
        jBtnConsolidado.setBackground(new Color(0,51,90));
        jBtnConsolidado.setForeground(Color.white);
    }//GEN-LAST:event_jBtnConsolidadoMouseExited

    private void jBtnConsolidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsolidadoActionPerformed
        // TODO add your handling code here:
        jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmConsolidado obb = new frmConsolidado();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnConsolidadoActionPerformed

    private void jBtnEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEstadoCuentaActionPerformed
        // TODO add your handling code here:
        
        jCallerImage.removeAll();
        jCallerImage.repaint();
        try {
            frmEstadoCuenta obb = new frmEstadoCuenta();
            this.jCallerImage.add(obb).setVisible(true);
            obb.setMaximum(true);
        } catch (PropertyVetoException ex) {
            System.out.println(ex.toString());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmFormularios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnEstadoCuentaActionPerformed

    private void jBtnEstadoCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEstadoCuentaMouseEntered
        // TODO add your handling code here:
        jBtnEstadoCuenta.setBackground(Color.white);
        jBtnEstadoCuenta.setForeground(Color.black);
    }//GEN-LAST:event_jBtnEstadoCuentaMouseEntered

    private void jBtnEstadoCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEstadoCuentaMouseExited
        // TODO add your handling code here:
        jBtnEstadoCuenta.setBackground(new Color(0,51,90));
        jBtnEstadoCuenta.setForeground(Color.white);
    }//GEN-LAST:event_jBtnEstadoCuentaMouseExited

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentRemoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFormularios().setVisible(true);
            }
        });
    
        try {
        
            FileInputStream fis = new FileInputStream (System.getProperty(
                                   "user.dir") + "\\src\\servicios\\config.txt");
            Properties p = new Properties (System.getProperties());
            p.load(fis);
            System.setProperties(p);
        }
        catch (java.io.FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Archivo de Configuración"
                + " de acceso a datos \n no encontrado, revisar configuración",
                "Configuración de acceso", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }//Fin de la instrucción catch
        
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error en lectura de datos "
                                        + "de inicio de configuración   \n",
                                         "Error al leer configuración", 
                                         JOptionPane.ERROR_MESSAGE);
            System.exit(0);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnBecas;
    public javax.swing.JButton jBtnConfiguracion;
    public javax.swing.JButton jBtnConsolidado;
    public javax.swing.JButton jBtnCoordinador;
    public javax.swing.JButton jBtnDeuda;
    public javax.swing.JButton jBtnEstadoCuenta;
    public javax.swing.JButton jBtnMaestrante;
    public javax.swing.JButton jBtnPagos;
    private javax.swing.JButton jBtnmaximizar;
    private javax.swing.JButton jBtnminimizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public javax.swing.JPanel jCallerImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jLbPrincipalPanel;
    public javax.swing.JLabel jLblMaes;
    public javax.swing.JLabel jLblUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jfecha1;
    private javax.swing.JLabel jtime;
    // End of variables declaration//GEN-END:variables


}
