/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GuiFormularios;

import Controlador.Ctr_Beca;
import Negocio.Beca;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESTUDIANTES
 */
public class frmBeca extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBeca
     */
    public frmBeca()throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException{
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBtnguardar = new javax.swing.JButton();
        jBtnbuscar = new javax.swing.JButton();
        jBtnactualizar = new javax.swing.JButton();
        jBtnListar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxpPatrocinadores = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jTxttotalbeca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCmbMaestrante = new javax.swing.JComboBox<>();
        jFmtfCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblCodigos = new javax.swing.JTable();
        pnlPaginar = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/beca.png"))); // NOI18N
        jLabel6.setText("Registro de Beca");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnguardar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnguardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnguardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/guardar_24.gif"))); // NOI18N
        jBtnguardar.setText("Guardar");
        jBtnguardar.setBorder(null);
        jBtnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnguardarMouseExited(evt);
            }
        });
        jBtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnguardarActionPerformed(evt);
            }
        });

        jBtnbuscar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnbuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/buscar_24.gif"))); // NOI18N
        jBtnbuscar.setText("Buscar");
        jBtnbuscar.setBorder(null);
        jBtnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnbuscarMouseExited(evt);
            }
        });
        jBtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnbuscarActionPerformed(evt);
            }
        });

        jBtnactualizar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnactualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/chk_24.png"))); // NOI18N
        jBtnactualizar.setText("Actualizar");
        jBtnactualizar.setBorder(null);
        jBtnactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnactualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnactualizarMouseExited(evt);
            }
        });
        jBtnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnactualizarActionPerformed(evt);
            }
        });

        jBtnListar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnListar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/listar_24.jpg"))); // NOI18N
        jBtnListar.setText("Listar");
        jBtnListar.setBorder(null);
        jBtnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnListarMouseExited(evt);
            }
        });
        jBtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 90));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/limpieza-de-datos.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Patrocinador(es) de la Beca");

        jTxpPatrocinadores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jTxpPatrocinadores);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Total de las Beca %");

        jTxttotalbeca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTxttotalbeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxttotalbecaMouseClicked(evt);
            }
        });
        jTxttotalbeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxttotalbecaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Código");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Maestrante");

        jCmbMaestrante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jCmbMaestrante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jFmtfCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxttotalbeca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCmbMaestrante, javax.swing.GroupLayout.Alignment.LEADING, 0, 178, Short.MAX_VALUE))
                    .addComponent(jFmtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFmtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxttotalbeca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbMaestrante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(25, 25, 25))
        );

        jTblCodigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Códigos"
            }
        ));
        jScrollPane2.setViewportView(jTblCodigos);

        pnlPaginar.setBackground(new java.awt.Color(0, 51, 90));

        javax.swing.GroupLayout pnlPaginarLayout = new javax.swing.GroupLayout(pnlPaginar);
        pnlPaginar.setLayout(pnlPaginarLayout);
        pnlPaginarLayout.setHorizontalGroup(
            pnlPaginarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPaginarLayout.setVerticalGroup(
            pnlPaginarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPaginar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlPaginar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnguardarActionPerformed

        try {
            int rst = Ctr_Beca.agregar(
                    Integer.parseInt(this.jFmtfCodigo.getText()),
                    this.jTxpPatrocinadores.getText(),
                    Integer.parseInt(this.jTxttotalbeca.getText()),
                    this.jCmbMaestrante.getSelectedIndex());

            limpiarRregistro();
            if (rst > 0) {
                JOptionPane.showMessageDialog(this, "Registro grabado con exito",
                         "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
            }//Fin de la instrucción if
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería" + ex.toString(),
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia" + ex.toString(),
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                    + "intentar utilizar \n la librería o instancia para guardar" + ex.toString(),
                    "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                    + "el manejo de la solicitud \n en recurso de Base de Datos" + ex.toString(),
                    "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnguardarActionPerformed

    public void limpiarRregistro() {
        this.jFmtfCodigo.setText("");
        this.jTxpPatrocinadores.setText("");
        this.jTxttotalbeca.setText("");
        this.jCmbMaestrante.setSelectedIndex(0);
    }

    public boolean validacion() {
        boolean valido = true;
        if (jFmtfCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La caja de texto  Número de carnet esta vacia.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return valido;
    }
    private void jBtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnbuscarActionPerformed
       
        if (validacion() == true) {
            try {
                int val = Integer.parseInt(this.jFmtfCodigo.getText());
                Beca p = Ctr_Beca.leerRegistro(val);

                if (p != null) {
                    this.jFmtfCodigo.setText(Integer.toString(p.getCodigo()));
                    this.jTxpPatrocinadores.setText(p.getPatrocinadoresBecas());
                    this.jTxttotalbeca.setText(Integer.toString(p.getBeca()));
                    this.jCmbMaestrante.setSelectedIndex(p.getID_Maestrante());
                }

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                        + "el \n registro, no se encuentra una librería" + ex.toString(), "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
            } catch (InstantiationException ex) {
                JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                        + "hacer referencia \n de una instancia" + ex.toString(),
                        "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalAccessException ex) {
                JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al "
                        + "intentar utilizar \n la librería o instancia para guardar" + ex.toString(),
                        "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Se ha producido una falla con " + ex.toString()
                        + "el manejo de la solicitud \n en recurso de Base de Datos"
                        + ex.getMessage(),
                        "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La caja de texto  Numero de carnet esta vacia.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnbuscarActionPerformed

    private void jBtnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnactualizarActionPerformed
   
        try {

            int val = Integer.parseInt(this.jFmtfCodigo.getText());
            Ctr_Beca Cpt = new Ctr_Beca();
            int id = Cpt.buscarId(val);

            if (id > 0) {
                int rst = Ctr_Beca.actualizar(
                        Integer.parseInt(this.jFmtfCodigo.getText()),
                        this.jTxpPatrocinadores.getText(),
                        Integer.parseInt(this.jTxttotalbeca.getText()),
                        this.jCmbMaestrante.getSelectedIndex(), id);
                if (rst > 0) {
                    JOptionPane.showMessageDialog(this, "Registro actualizado con exito",
                            "Actualizar Registro", JOptionPane.INFORMATION_MESSAGE);

                    limpiarRregistro();

                }
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería" + ex.toString(),
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia" + ex.toString(),
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                    + "intentar utilizar \n la librería o instancia para guardar" + ex.toString(),
                    "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                    + "el manejo de la solicitud \n en recurso de Base de Datos" + ex.toString(),
                    "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnactualizarActionPerformed

    private void jBtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarActionPerformed

        try {
            Ctr_Beca.listar(jTblCodigos);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería" + ex.toString(),
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia" + ex.toString(),
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                    + "intentar utilizar \n la librería o instancia para guardar" + ex.toString(),
                    "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                    + "el manejo de la solicitud \n al intentar registrar datos " + ex.toString()
                    + ex.getSQLState(),
                    "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnListarActionPerformed

    private void jTxttotalbecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxttotalbecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxttotalbecaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        try {
            //1. Cargar la lista de Facultades
            for (String name : Ctr_Beca.CargarCombobox()) {
                this.jCmbMaestrante.addItem(name);
            }//Fin de for        
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se ha provocado una falla"
                    + "al tratar de listar los Numeros de Carnet de los Maestrantes\n "
                    + " registrados actualmente", "Error al cargar"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_formInternalFrameActivated

    private void jTxttotalbecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxttotalbecaMouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jTxttotalbecaMouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.black);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,51,90));
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTblCodigos.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnguardarMouseEntered
        // TODO add your handling code here:
         jBtnguardar.setBackground(Color.white);
         jBtnguardar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnguardarMouseEntered

    private void jBtnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnguardarMouseExited
        // TODO add your handling code here:
         jBtnguardar.setBackground(new Color (0,51,90));
         jBtnguardar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnguardarMouseExited

    private void jBtnbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnbuscarMouseEntered
        // TODO add your handling code here:
        jBtnbuscar.setBackground(Color.white);
         jBtnbuscar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnbuscarMouseEntered

    private void jBtnbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnbuscarMouseExited
        // TODO add your handling code here:
         jBtnbuscar.setBackground(new Color (0,51,90));
         jBtnbuscar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnbuscarMouseExited

    private void jBtnactualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnactualizarMouseEntered
        // TODO add your handling code here:
         jBtnactualizar.setBackground(Color.white);
         jBtnactualizar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnactualizarMouseEntered

    private void jBtnactualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnactualizarMouseExited
        // TODO add your handling code here:
        jBtnactualizar.setBackground(new Color (0,51,90));
         jBtnactualizar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnactualizarMouseExited

    private void jBtnListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnListarMouseEntered
        // TODO add your handling code here:
         jBtnListar.setBackground(Color.white);
         jBtnListar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnListarMouseEntered

    private void jBtnListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnListarMouseExited
        // TODO add your handling code here:
        jBtnListar.setBackground(new Color (0,51,90));
         jBtnListar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnListarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnListar;
    private javax.swing.JButton jBtnactualizar;
    private javax.swing.JButton jBtnbuscar;
    private javax.swing.JButton jBtnguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCmbMaestrante;
    private javax.swing.JTextField jFmtfCodigo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblCodigos;
    private javax.swing.JTextPane jTxpPatrocinadores;
    public javax.swing.JTextField jTxttotalbeca;
    private javax.swing.JPanel pnlPaginar;
    // End of variables declaration//GEN-END:variables
}
