/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GuiFormularios;
import Controlador.Ctr_Coordinador;
import Negocio.UsuarioCoordinador;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Diego Silva
 */
public class frmCoordinador extends javax.swing.JInternalFrame {

    
    UsuarioCoordinador usocor = new UsuarioCoordinador();
    /**
     * Creates new form frmCoordinador
     */
    public frmCoordinador()throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        initComponents();
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
            // Obtener el encabezado de la tabla
            JTableHeader header = jTblCoordinador.getTableHeader();
            
            // Establecer el color de fondo del encabezado
            header.setBackground(Color.yellow);
    
    }
                
    


  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBtnbuscar = new javax.swing.JButton();
        jBtnguardar = new javax.swing.JButton();
        jBtnactualizar = new javax.swing.JButton();
        jBtneliminar = new javax.swing.JButton();
        jBtnListar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jFtfnumcarnetb = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtapellido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtEstado = new javax.swing.JTextField();
        jDtcFechaIC = new javax.swing.JFormattedTextField();
        jDtcFechaFC = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCoordinador = new javax.swing.JTable();
        pnlPaginar = new javax.swing.JPanel();

        setBorder(null);
        setClosable(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/coordinador.png"))); // NOI18N
        jLabel6.setText("Registro de Coordinador");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtnbuscar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnbuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/buscar_24.gif"))); // NOI18N
        jBtnbuscar.setText("Buscar");
        jBtnbuscar.setBorder(null);
        jBtnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnbuscarMouseExited(evt);
            }
        });
        jBtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnbuscarActionPerformed(evt);
            }
        });

        jBtnguardar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnguardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnguardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/guardar_24.gif"))); // NOI18N
        jBtnguardar.setText("Guardar");
        jBtnguardar.setBorder(null);
        jBtnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnguardarMouseExited(evt);
            }
        });
        jBtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnguardarActionPerformed(evt);
            }
        });

        jBtnactualizar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnactualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/chk_24.png"))); // NOI18N
        jBtnactualizar.setText("Actualizar");
        jBtnactualizar.setBorder(null);
        jBtnactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnactualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnactualizarMouseExited(evt);
            }
        });
        jBtnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnactualizarActionPerformed(evt);
            }
        });

        jBtneliminar.setBackground(new java.awt.Color(0, 51, 90));
        jBtneliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtneliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/elimina_24.png"))); // NOI18N
        jBtneliminar.setText("Baja");
        jBtneliminar.setBorder(null);
        jBtneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtneliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtneliminarMouseExited(evt);
            }
        });
        jBtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtneliminarActionPerformed(evt);
            }
        });

        jBtnListar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnListar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/listar_24.jpg"))); // NOI18N
        jBtnListar.setText("Listar");
        jBtnListar.setBorder(null);
        jBtnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnListarMouseExited(evt);
            }
        });
        jBtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 90));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/limpieza-de-datos.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jBtnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jBtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lupa (2).png"))); // NOI18N
        jLabel10.setText("N° Carnet");

        jFtfnumcarnetb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jFtfnumcarnetb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Nombres");

        jTxtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Apellidos");

        jTxtapellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTxtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtapellidoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Fecha de Inicio del Corte");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Fecha de Fin del Corte");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lupa (2).png"))); // NOI18N
        jLabel13.setText("Estado");

        jtxtEstado.setEditable(false);
        jtxtEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtxtEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jDtcFechaIC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDtcFechaIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jDtcFechaFC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDtcFechaFC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDtcFechaFC, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jFtfnumcarnetb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtapellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDtcFechaIC, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtEstado))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFtfnumcarnetb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTxtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jDtcFechaIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jDtcFechaFC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTblCoordinador.setAutoCreateRowSorter(true);
        jTblCoordinador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Carnet", "Nombres", "Apellidos", "Fecha de Inicio del Corte", "Fecha de Fin del Corte", "Estado"
            }
        ));
        jTblCoordinador.setColumnSelectionAllowed(true);
        jTblCoordinador.setGridColor(new java.awt.Color(255, 204, 0));
        jTblCoordinador.setOpaque(false);
        jTblCoordinador.setRowHeight(30);
        jTblCoordinador.setRowMargin(10);
        jTblCoordinador.setSelectionBackground(new java.awt.Color(0, 204, 0));
        jTblCoordinador.setShowGrid(true);
        jScrollPane1.setViewportView(jTblCoordinador);

        pnlPaginar.setBackground(new java.awt.Color(0, 51, 90));

        javax.swing.GroupLayout pnlPaginarLayout = new javax.swing.GroupLayout(pnlPaginar);
        pnlPaginar.setLayout(pnlPaginarLayout);
        pnlPaginarLayout.setHorizontalGroup(
            pnlPaginarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPaginarLayout.setVerticalGroup(
            pnlPaginarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPaginar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel6)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(pnlPaginar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtapellidoActionPerformed

    private void jBtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnbuscarActionPerformed
        // TODO add your handling code here:
            
    if (validacion() == true) {
                           try {
                                // Realizar el filtrado de un registro indicado por inns:
                                int val = Integer.parseInt(this.jFtfnumcarnetb.getText());
                                UsuarioCoordinador p = Ctr_Coordinador.leerRegistro(val);
                
                                //Si se obtuvo el registro, se muestra
                                if (p != null) {
                                        this.jTxtNombre.setText(p.getNombres());
                                        this.jTxtapellido.setText(p.getApellidos());
                                        this.jDtcFechaIC.setText(p.getFechaInicioCorte());
                                        this.jDtcFechaFC.setText(p.getFechaFinCorte());
                                        this.jtxtEstado.setText(p.getEstado());
                                        
                                        if(p.getEstado().equals("Activo")){
                                            jtxtEstado.setBackground(Color.GREEN);
                                        }
                                        else if(p.getEstado().equals("Inactivo")){
                                            jtxtEstado.setBackground(Color.RED);
                                        }
                                    }//Fin de la instrucción if
                
                            } catch (ClassNotFoundException ex) {
                                JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                                        + "el \n registro, no se encuentra una librería"+ex.toString(), "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
                            } catch (InstantiationException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                                        + "hacer referencia \n de una instancia"+ex.toString(),
                                        "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
                            } catch (IllegalAccessException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al "
                                        + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(), "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                                        + "el manejo de la solicitud \n en recurso de Base de Datos"+ex.toString()
                                        + ex.getMessage(),
                                        "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
                            }
                    }
                else
                {
                        JOptionPane.showMessageDialog(null, "La caja de texto  Numero de carnet esta vacia.",
                                "Error de validación", JOptionPane.ERROR_MESSAGE);
                    }
    }//GEN-LAST:event_jBtnbuscarActionPerformed

      
    private void jBtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnguardarActionPerformed
   
        
            try {
                        int rst;
                        
                rst = Ctr_Coordinador.agregar(
                        Integer.parseInt(this.jFtfnumcarnetb.getText()),
                        this.jTxtNombre.getText(),
                        this.jTxtapellido.getText(),
                        this.jDtcFechaIC.getText(), 
                        this.jDtcFechaFC.getText()
                        );
                                
                        limpiarRregistro();
                        
                        if (rst > 0 ) {
                                JOptionPane.showMessageDialog(this, "Registro grabado con exito"
                                        , "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
                            }//Fin de la instrucción if
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                                + "el \n registro, no se encuentra una librería"+ex.toString(),
                                "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
                    } catch (InstantiationException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                                + "hacer referencia \n de una instancia"+ex.toString(),
                                "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
                    } catch (IllegalAccessException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                                + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(),
                                "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                                + "el manejo de la solicitud \n en recurso de Base de Datos"+ex.toString(),
                                "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
                    }
    }//GEN-LAST:event_jBtnguardarActionPerformed

    private void jBtnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnactualizarActionPerformed
        // TODO add your handling code here:
         try {
            
            int val = Integer.parseInt(this.jFtfnumcarnetb.getText());
            Ctr_Coordinador Cpt = new Ctr_Coordinador();
            int id = Cpt.buscarId(val);

            if (id > 0) {
               int rst = Ctr_Coordinador.actualizar(
       Integer.parseInt(this.jFtfnumcarnetb.getText()),
                        this.jTxtNombre.getText(),
                        this.jTxtapellido.getText(),
                        this.jDtcFechaIC.getText(),
                        this.jDtcFechaFC.getText(),id); 
                if (rst > 0) {
                    JOptionPane.showMessageDialog(this, "Registro actualizado con exito",
                             "Actualizar Registro", JOptionPane.INFORMATION_MESSAGE);

                      limpiarRregistro();

                }
            }  
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería"+ex.toString(), 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia"+ex.toString(), 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar", 
                  "Acceso Ilegal a un Recurso"+ex.toString(), JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n en recurso de Base de Datos"+ex.toString(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnactualizarActionPerformed

    private void jBtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarActionPerformed

        try {
            Ctr_Coordinador.listar(jTblCoordinador);  
            
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                + "el \n registro, no se encuentra una librería"+ex.toString(),
                "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                + "hacer referencia \n de una instancia"+ex.toString(),
                "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(),
                "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                + "el manejo de la solicitud \n al intentar registrar datos "+ex.toString()
                + ex.getSQLState(),
                "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnListarActionPerformed

    private void jBtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtneliminarActionPerformed
        
        int opc;      
        try {
            opc = JOptionPane.showConfirmDialog(this, "Esta intentando eliminar"
                                            + " un registro que contiene más \n"
                                            + " vinculaciones con otros datos"
                                            + " ¿Esta seguro de continuar?" ,                    
                                      "Eliminar", JOptionPane.YES_NO_OPTION, 
                                      JOptionPane.WARNING_MESSAGE);
            if (opc == JOptionPane.YES_OPTION)
                Ctr_Coordinador.eliminar(Integer.parseInt(this.jFtfnumcarnetb.getText()));
                JOptionPane.showMessageDialog(this, "El registro del Empleado:"
                                             + this.jFtfnumcarnetb.getText() + 
                                             "\n ha sido removido", "Eliminar",
                                             JOptionPane.INFORMATION_MESSAGE);
                this.limpiarRregistro();
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería"+ex.toString(), 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia"+ex.toString(), 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(), 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n al intentar registrar datos "+ex.toString()
                  + ex.getSQLState(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBtneliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTblCoordinador.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnguardarMouseEntered
        // TODO add your handling code here:
        jBtnguardar.setBackground(Color.white);
        jBtnguardar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnguardarMouseEntered

    private void jBtnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnguardarMouseExited
        // TODO add your handling code here:
        jBtnguardar.setBackground(new Color(0,51,90));
        jBtnguardar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnguardarMouseExited

    private void jBtnbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnbuscarMouseEntered
        // TODO add your handling code here:
        jBtnbuscar.setBackground(Color.white);
        jBtnbuscar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnbuscarMouseEntered

    private void jBtnbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnbuscarMouseExited
        // TODO add your handling code here:
         jBtnbuscar.setBackground(new Color(0,51,90));
         jBtnbuscar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnbuscarMouseExited

    private void jBtnactualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnactualizarMouseEntered
        // TODO add your handling code here:
        jBtnactualizar.setBackground(Color.white);
        jBtnactualizar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnactualizarMouseEntered

    private void jBtnactualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnactualizarMouseExited
        // TODO add your handling code here:
        jBtnactualizar.setBackground(new Color(0,51,90));
        jBtnactualizar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnactualizarMouseExited

    private void jBtneliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtneliminarMouseEntered
        // TODO add your handling code here:
        jBtneliminar.setBackground(Color.white);
        jBtneliminar.setForeground(Color.black);
    }//GEN-LAST:event_jBtneliminarMouseEntered

    private void jBtneliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtneliminarMouseExited
        // TODO add your handling code here:
        jBtneliminar.setBackground(new Color(0,51,90));
        jBtneliminar.setForeground(Color.white);
    }//GEN-LAST:event_jBtneliminarMouseExited

    private void jBtnListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnListarMouseEntered
        // TODO add your handling code here:
        jBtnListar.setBackground(Color.white);
        jBtnListar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnListarMouseEntered

    private void jBtnListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnListarMouseExited
        // TODO add your handling code here:
        jBtnListar.setBackground(new Color(0,51,90));
        jBtnListar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnListarMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.black);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,51,90));
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

       public boolean validacion(){
            boolean valido = true;  
        if (jFtfnumcarnetb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La caja de texto  Número de carnet esta vacia.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }
         return valido;
    }
        public void limpiarRregistro() 
        {
        this.jTxtNombre.setText("");
        this.jTxtapellido.setText("");
        this.jFtfnumcarnetb.setText("");
        this.jDtcFechaIC.setText("");
        this.jDtcFechaFC.setText("");
        this.jtxtEstado.setText("");
        this.jtxtEstado.setBackground(Color.WHITE);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnListar;
    private javax.swing.JButton jBtnactualizar;
    private javax.swing.JButton jBtnbuscar;
    private javax.swing.JButton jBtneliminar;
    private javax.swing.JButton jBtnguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jDtcFechaFC;
    private javax.swing.JFormattedTextField jDtcFechaIC;
    private javax.swing.JFormattedTextField jFtfnumcarnetb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCoordinador;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtapellido;
    private javax.swing.JTextField jtxtEstado;
    private javax.swing.JPanel pnlPaginar;
    // End of variables declaration//GEN-END:variables

}
