/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GuiFormularios;
import Datos.BDLogin;
import Controlador.Ctr_Login;
import Gui.frmFormularios;
import Negocio.Login;
import Servicios.Conexion;
import Servicios.MS_SQLServer;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Tania Silva
 */
public class frmLogin extends javax.swing.JInternalFrame{
private MS_SQLServer cnx = null; 

//private BSDatos metodos = null;
 BDLogin metodos = new BDLogin();
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        btnGenerador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtPassword = new javax.swing.JPasswordField();
        jRbtshowHide = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBtnIniciar = new javax.swing.JButton();
        jBrtRegistar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/usuario (2).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Usuario");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setText("Contraseña");

        jTxtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsuarioActionPerformed(evt);
            }
        });

        btnGenerador.setFont(new java.awt.Font("Monotype Corsiva", 1, 14)); // NOI18N
        btnGenerador.setForeground(new java.awt.Color(255, 204, 0));
        btnGenerador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/contrasena.png"))); // NOI18N
        btnGenerador.setBorder(null);
        btnGenerador.setContentAreaFilled(false);
        btnGenerador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGeneradorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGeneradorMouseExited(evt);
            }
        });
        btnGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneradorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        jLabel2.setText("Inicio de sesión");

        jTxtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRbtshowHide.setBackground(new java.awt.Color(255, 255, 255));
        jRbtshowHide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRbtshowHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/ojo.png"))); // NOI18N
        jRbtshowHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbtshowHideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRbtshowHideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jRbtshowHideMouseExited(evt);
            }
        });
        jRbtshowHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtshowHideActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 50, 91));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/unanazulchiquito.PNG"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Unan-Managua");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cerrar-ventana (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBtnIniciar.setBackground(new java.awt.Color(0, 50, 91));
        jBtnIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIniciar.setText("Iniciar");
        jBtnIniciar.setBorder(null);
        jBtnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnIniciarMouseExited(evt);
            }
        });
        jBtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIniciarActionPerformed(evt);
            }
        });

        jBrtRegistar.setBackground(new java.awt.Color(0, 51, 90));
        jBrtRegistar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBrtRegistar.setForeground(new java.awt.Color(255, 255, 255));
        jBrtRegistar.setText("Registrar");
        jBrtRegistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBrtRegistarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBrtRegistarMouseExited(evt);
            }
        });
        jBrtRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrtRegistarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBrtRegistar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jTxtPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGenerador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRbtshowHide)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGenerador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jRbtshowHide, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBrtRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUsuarioActionPerformed
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneradorActionPerformed
        // TODO add your handling code here:
        char [] Mayusculas = {'A','B','C','D','E','F','G'};
        char [] minusculas = {'a','b','c','d','e','f','g'};
        char [] Numeros = {'1','2','3','4','5','6','7','8','9','0'};

        StringBuilder caracteres = new StringBuilder();

        caracteres.append(Mayusculas);
        caracteres.append(minusculas);
        caracteres.append(Numeros);

        StringBuilder contrasenia = new StringBuilder();

        for (int i = 0; i<8; i++){

            int cantidadCaracteres = caracteres.length();
            int numeroRandom = (int)(Math.random()*cantidadCaracteres);
            contrasenia.append((caracteres.toString()).charAt(numeroRandom));
        }
        this.jTxtPassword.setText(contrasenia.toString());
        JOptionPane.showMessageDialog(null, "Se ha generado una contraseña para su Usuario\n"+jTxtUsuario.getText());

    }//GEN-LAST:event_btnGeneradorActionPerformed

    private void btnGeneradorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneradorMouseExited
        // TODO add your handling code here:
         btnGenerador.setBackground(new Color(0,51,90));
        
    }//GEN-LAST:event_btnGeneradorMouseExited

    private void btnGeneradorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneradorMouseEntered
        // TODO add your handling code here:
        btnGenerador.setBackground(Color.white);
    }//GEN-LAST:event_btnGeneradorMouseEntered

    private void jRbtshowHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtshowHideActionPerformed
        // TODO add your handling code here:
        if (jRbtshowHide.isSelected()){
            jTxtPassword.setEchoChar((char)0);
        }
        else{
            jTxtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jRbtshowHideActionPerformed

    private void jRbtshowHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtshowHideMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jRbtshowHideMouseClicked

    private void jRbtshowHideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtshowHideMouseEntered
        // TODO add your handling code here:
        btnGenerador.setBackground(Color.white);
        
    }//GEN-LAST:event_jRbtshowHideMouseEntered

    private void jRbtshowHideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtshowHideMouseExited
        // TODO add your handling code here:
        btnGenerador.setBackground(new Color(0,51,90));
    }//GEN-LAST:event_jRbtshowHideMouseExited

    private void jBtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIniciarActionPerformed
        // TODO add your handling code here:
        if(this.validarcampos()){
           
           String Usuario = jTxtUsuario.getText();
           String Contraseña = jTxtPassword.getText();
           
           String url = "Select Usuario, Contraseña, Privilegio from UsuariosRoles where Usuario ='"+Usuario+"'";
           
      try{
        cnx = new MS_SQLServer ();
        cnx.pst = cnx.conexion.prepareStatement(url);
        cnx.resultado = cnx.pst.executeQuery();
        
        if(cnx.resultado.next()){
            
            String User = cnx.resultado.getString("Usuario");
            String Contra = cnx.resultado.getString("Contraseña");
            String Priv = cnx.resultado.getString("Privilegio");
            
            
            if(Contraseña.equals(Contra)){
                
                if(Priv.equals("Maestrante")){
                    frmFormularios form = new frmFormularios();
                    form.jLblUser.setText(jTxtUsuario.getText());
                    form.jLblMaes.setText("Maestrante:");
                    form.jPanel4.setVisible(true);
                    form.jBtnMaestrante.setVisible(false);
                    form.jBtnPagos.setVisible(false);
                    form.jBtnCoordinador.setVisible(false);
                    form.jBtnBecas.setVisible(false);
                    form.jBtnDeuda.setVisible(false);
                    form.jBtnConfiguracion.setVisible(false);
                    form.jBtnConsolidado.setVisible(false);
                    JOptionPane.showMessageDialog(null,"Bienvenido Maestrante:"+Usuario);
                    this.dispose();
                                     
                }
                else if(Priv.equals("Coordinador")){
                   frmFormularios form = new frmFormularios();                
                    form.jLblUser.setText(jTxtUsuario.getText());
                    form.jLblMaes.setText("Coordinador:");
                    form.jPanel4.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null,"Bienvenido Coordinador:"+Usuario);
                }
                
            }else{
                JOptionPane.showMessageDialog(null,"Contraseña Incorrecta, Revice de Nuevo");
            }
        }else{
              JOptionPane.showMessageDialog(null,"Este Usuario no esta registrado");
        }
        }catch(ClassNotFoundException ex){    JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                                        + "el \n registro, no se encuentra una librería", "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
                            } catch (InstantiationException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                                        + "hacer referencia \n de una instancia",
                                        "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
                            } catch (IllegalAccessException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al "
                                        + "intentar utilizar \n la librería o instancia para guardar", "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                                        + "el manejo de la solicitud \n en recurso de Base de Datos"
                                        + ex.getMessage(),
                                        "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
                            }
    }   
    }//GEN-LAST:event_jBtnIniciarActionPerformed

    private void jBtnIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnIniciarMouseEntered
        // TODO add your handling code here:
        jBtnIniciar.setBackground(Color.white);
        jBtnIniciar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnIniciarMouseEntered

    private void jBtnIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnIniciarMouseExited
        // TODO add your handling code here:
        jBtnIniciar.setBackground(new Color(0,51,90));
        jBtnIniciar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnIniciarMouseExited

    private void jBrtRegistarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBrtRegistarMouseEntered
        // TODO add your handling code here:
        jBrtRegistar.setBackground(Color.white);
        jBrtRegistar.setForeground(Color.black);
    }//GEN-LAST:event_jBrtRegistarMouseEntered

    private void jBrtRegistarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBrtRegistarMouseExited
        // TODO add your handling code here:
        jBrtRegistar.setBackground(new Color(0,51,90));
        jBrtRegistar.setForeground(Color.white);
    }//GEN-LAST:event_jBrtRegistarMouseExited

    private void jBrtRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrtRegistarActionPerformed
        // TODO add your handling code here:
         try {
                        int rst;
                        
                rst = Ctr_Login.agregar(
                        this.jTxtUsuario.getText(),
                        this.jTxtPassword.getText()
                        );
                                
                        limpiarRregistro();
                        
                        if (rst > 0 ) {
                                JOptionPane.showMessageDialog(this, "Registro grabado con exito"
                                        , "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
                            }//Fin de la instrucción if
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                                + "el \n registro, no se encuentra una librería"+ex.toString(),
                                "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
                    } catch (InstantiationException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                                + "hacer referencia \n de una instancia"+ex.toString(),
                                "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
                    } catch (IllegalAccessException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                                + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(),
                                "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                                + "el manejo de la solicitud \n en recurso de Base de Datos"+ex.toString(),
                                "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
                    }
        
        
    }//GEN-LAST:event_jBrtRegistarActionPerformed
  
    public void limpiarRregistro() {

        this.jTxtUsuario.setText("");
        jTxtPassword.setText("");
    }

    private boolean validarcampos() {
        boolean Valido = true;
        if (jTxtUsuario.getText().isBlank() || jTxtPassword.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos. Por favor, ingrese los datos correctamente.");
            return false;
        }
        return Valido;
    }

    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerador;
    private javax.swing.JButton jBrtRegistar;
    private javax.swing.JButton jBtnIniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRbtshowHide;
    private javax.swing.JPasswordField jTxtPassword;
    public javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables

}
