/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GuiFormularios;

import Controlador.Ctr_Maestrante;
import Negocio.UsuarioMaestrante;
import Pagination.EventPagination;
import Pagination.style.PaginationItemRenderStyle1;
import java.awt.Color;
import java.awt.Component;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
/**
 *
 * @author Estudiante
 */


public class frmRegistroMaestrante extends javax.swing.JInternalFrame {

    private int totalFilas; // Variable para almacenar el total de filas obtenidas
    private int filasPorPagina = 10; // Número de filas a mostrar por página
    private int totalPaginas; // Variable para almacenar el total de páginas
    private int paginaActual = 1; // Página actual que se está mostrando
    private Object[] filasResultantes;

    public frmRegistroMaestrante()throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException{
        
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
//           pagination1.addEventPagination(new EventPagination() {
//            @Override
//            public void pageChanged(int page) {
//                try {
//                    LoadData(page);
//                    mostrarFilasPaginaActual(page);
//                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
//                    Logger.getLogger(frmRegistroMaestrante.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//           pagination1.setPaginationItemRender(new PaginationItemRenderStyle1());
//      try {
//                    LoadData(1);
//         
//                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException ex) {
//                    Logger.getLogger(frmRegistroMaestrante.class.getName()).log(Level.SEVERE, null, ex);
//                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBtnbuscar = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnactualizar = new javax.swing.JButton();
        jBtneliminar = new javax.swing.JButton();
        jBtnListar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtapellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jFtfnumcarnetb = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtingresos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCmCoordinador = new javax.swing.JComboBox<>();
        jCmbEstado = new javax.swing.JTextField();
        pnlPaginar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRusuario = new javax.swing.JTable();

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtnbuscar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnbuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/buscar_24.gif"))); // NOI18N
        jBtnbuscar.setText("Buscar");
        jBtnbuscar.setBorder(null);
        jBtnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnbuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnbuscarMouseExited(evt);
            }
        });
        jBtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnbuscarActionPerformed(evt);
            }
        });

        jBtnGuardar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/guardar_24.gif"))); // NOI18N
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setBorder(null);
        jBtnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnGuardarMouseExited(evt);
            }
        });
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnactualizar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnactualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnactualizar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/chk_24.png"))); // NOI18N
        jBtnactualizar.setText("Actualizar");
        jBtnactualizar.setBorder(null);
        jBtnactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnactualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnactualizarMouseExited(evt);
            }
        });
        jBtnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnactualizarActionPerformed(evt);
            }
        });

        jBtneliminar.setBackground(new java.awt.Color(0, 51, 90));
        jBtneliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtneliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/elimina_24.png"))); // NOI18N
        jBtneliminar.setText("Baja");
        jBtneliminar.setBorder(null);
        jBtneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtneliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtneliminarMouseExited(evt);
            }
        });
        jBtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtneliminarActionPerformed(evt);
            }
        });

        jBtnListar.setBackground(new java.awt.Color(0, 51, 90));
        jBtnListar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBtnListar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/listar_24.jpg"))); // NOI18N
        jBtnListar.setText("Listar");
        jBtnListar.setBorder(null);
        jBtnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnListarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnListarMouseExited(evt);
            }
        });
        jBtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnListarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 90));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/limpieza-de-datos.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtneliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/registro.png"))); // NOI18N
        jLabel6.setText("Registro de Maestrante");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Nombres");

        jTxtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Apellidos");

        jTxtapellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTxtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtapellidoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lupa (2).png"))); // NOI18N
        jLabel10.setText("N° Carnet");

        jFtfnumcarnetb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            jFtfnumcarnetb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Ingresos $");

        jTxtingresos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/lupa (2).png"))); // NOI18N
        jLabel12.setText("Estado");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/coordinador.png"))); // NOI18N
        jLabel13.setText("Coordinador");

        jCmCoordinador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jCmCoordinador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCmbEstado.setEditable(false);
        jCmbEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCmbEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCmCoordinador, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                    .addComponent(jTxtNombre)
                    .addComponent(jTxtapellido)
                    .addComponent(jTxtingresos)
                    .addComponent(jFtfnumcarnetb)
                    .addComponent(jCmbEstado))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFtfnumcarnetb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtingresos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCmCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlPaginar.setBackground(new java.awt.Color(0, 51, 90));

        javax.swing.GroupLayout pnlPaginarLayout = new javax.swing.GroupLayout(pnlPaginar);
        pnlPaginar.setLayout(pnlPaginarLayout);
        pnlPaginarLayout.setHorizontalGroup(
            pnlPaginarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        pnlPaginarLayout.setVerticalGroup(
            pnlPaginarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jTblRusuario.setAutoCreateRowSorter(true);
        jTblRusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTblRusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Carnet", "Nombres", "Apellidos", "Ingresos$", "Estado"
            }
        ));
        jTblRusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTblRusuario.setFocusCycleRoot(true);
        jTblRusuario.setGridColor(new java.awt.Color(255, 204, 0));
        jTblRusuario.setOpaque(false);
        jTblRusuario.setRowHeight(30);
        jTblRusuario.setRowMargin(10);
        jTblRusuario.setRowSelectionAllowed(false);
        jTblRusuario.setSelectionBackground(new java.awt.Color(0, 204, 0));
        jTblRusuario.setShowGrid(true);
        jTblRusuario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblRusuario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addComponent(pnlPaginar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPaginar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void LoadData(int page)throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException{
        
//        DefaultTableModel modelo = new DefaultTableModel();
//        jTblRusuario.setModel(modelo);
//
//        modelo.addColumn("N° Carnet");
//        modelo.addColumn("Nombres");
//        modelo.addColumn("Apellidos");
//        modelo.addColumn("Ingresos");
//        modelo.addColumn("Estado");
//        
//        Ctr_Maestrante obb = new Ctr_Maestrante();
//        filasResultantes = obb.Listado();
//        totalFilas = filasResultantes.length;
//        filasPorPagina = 15;
//        totalPaginas = (int) Math.ceil((double) totalFilas / filasPorPagina);
//        paginaActual = 1;
//        int filaInicial = (paginaActual - 1) * filasPorPagina;
//        int filaFinal = Math.min(filaInicial + filasPorPagina, totalFilas);
//
//        for (int i = filaInicial; i < filaFinal; i++) {
//            modelo.addRow((Object[]) filasResultantes[i]);
//        }
//
//        packColumns(jTblRusuario, 6);
//        // Obtener celda en la posición (0, 0)
//        Rectangle rect = jTblRusuario.getCellRect(0, 0, true);
//        jTblRusuario.scrollRectToVisible(rect);
//
//        totalFilas = filasResultantes.length;
//        totalPaginas = (int) Math.ceil((double) totalFilas / filasPorPagina);
//
//        // Mostrar las filas correspondientes a la página actual
//        mostrarFilasPaginaActual(page);
//        pagination1.setPagegination(page, totalPaginas);
//    }
//     private void packColumns(JTable table, int margin) {
//        for (int column = 0; column < table.getColumnCount(); column++) {
//            TableColumn tableColumn = table.getColumnModel().getColumn(column);
//            int width = margin; // Establecer un margen inicial
//
//            for (int row = 0; row < table.getRowCount(); row++) {
//                TableCellRenderer renderer = table.getCellRenderer(row, column);
//                Component comp = table.prepareRenderer(renderer, row, column);
//                width = Math.max(comp.getPreferredSize().width + margin, width);
//            }
//
//            tableColumn.setPreferredWidth(width);
//        }
//     }
//    private void mostrarFilasPaginaActual(int page) {
//        // Limpiar el modelo de tabla
//        DefaultTableModel modelo = (DefaultTableModel) jTblRusuario.getModel();
//        modelo.setRowCount(0);
//
//        // Calcular las filas inicial y final de la página actual
//        int filaInicial = (page - 1) * filasPorPagina;
//        int filaFinal = Math.min(filaInicial + filasPorPagina, totalFilas);
//
//        // Verificar que el número de filas resultantes sea válido
//        if (filasResultantes != null && filaInicial >= 0 && filaInicial < filasResultantes.length && filaFinal <= filasResultantes.length) {
//            // Agregar las filas correspondientes a la página actual al modelo de tabla
//            for (int i = filaInicial; i < filaFinal; i++) {
//                modelo.addRow((Object[]) filasResultantes[i]);
//            }
//        }
//
//        // Actualizar la visualización de la tabla
//        jTblRusuario.repaint();
    }
    
    private void jTxtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtapellidoActionPerformed

    private void jBtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnbuscarActionPerformed
        // TODO add your handling code here:

                if (validacion() == true) {
                        try {
                                int val = Integer.parseInt(this.jFtfnumcarnetb.getText());
                                UsuarioMaestrante p = Ctr_Maestrante.leerRegistro(val);

                                if (p != null) {
                                        this.jTxtNombre.setText(p.getNombre());
                                        this.jTxtapellido.setText(p.getApellido());
                                        this.jTxtingresos.setText(Double.toString(p.getIngresoMaestrante()));
                                        this.jCmbEstado.setText(p.getEstado());
                                        this.jCmCoordinador.setSelectedIndex(p.getIdCoordinadador());
                                       if(p.getEstado().equals("Activo")){
                                            jCmbEstado.setBackground(Color.GREEN);
                                        }
                                        else if(p.getEstado().equals("Inactivo")){
                                            jCmbEstado.setBackground(Color.RED);
                                        }
                                }
                            } catch (ClassNotFoundException ex) {
                                JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                                        + "el \n registro, no se encuentra una librería", "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
                            } catch (InstantiationException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                                        + "hacer referencia \n de una instancia",
                                        "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
                            } catch (IllegalAccessException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al "
                                        + "intentar utilizar \n la librería o instancia para guardar", "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                                        + "el manejo de la solicitud \n en recurso de Base de Datos"
                                        + ex.getMessage(),
                                        "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
                            }
                    }
                else
                {
                        JOptionPane.showMessageDialog(null, "La caja de texto  Numero de carnet esta vacia.",
                                "Error de validación", JOptionPane.ERROR_MESSAGE);
                    }
    }//GEN-LAST:event_jBtnbuscarActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
                try {
                        int rst = Ctr_Maestrante.agregar(Integer.parseInt(this.jFtfnumcarnetb.getText()),
                                this.jTxtNombre.getText(),
                                this.jTxtapellido.getText(),
                                Double.parseDouble(this.jTxtingresos.getText()),
                                this.jCmCoordinador.getSelectedIndex());

                        limpiarRregistro();
                        if (rst > 0 ) {
                                JOptionPane.showMessageDialog(this, "Registro grabado con exito"
                                        , "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
                            }//Fin de la instrucción if
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                                + "el \n registro, no se encuentra una librería"+ex.toString(),
                                "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
                    } catch (InstantiationException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                                + "hacer referencia \n de una instancia"+ex.toString(),
                                "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
                    } catch (IllegalAccessException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                                + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(),
                                "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                                + "el manejo de la solicitud \n en recurso de Base de Datos"+ex.toString(),
                                "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
                    }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnactualizarActionPerformed
        // TODO add your handling code here:
        try {
            
            int val = Integer.parseInt(this.jFtfnumcarnetb.getText());
            Ctr_Maestrante Cpt = new Ctr_Maestrante();
            int id = Cpt.buscarId(val);

            if (id > 0) {
               int rst = Ctr_Maestrante.actualizar(
       Integer.parseInt(this.jFtfnumcarnetb.getText()),
                        this.jTxtNombre.getText(),
                        this.jTxtapellido.getText(),
                        Double.parseDouble(this.jTxtingresos.getText()),
                        this.jCmCoordinador.getSelectedIndex(),id); 
                if (rst > 0) {
                    JOptionPane.showMessageDialog(this, "Registro actualizado con exito",
                             "Actualizar Registro", JOptionPane.INFORMATION_MESSAGE);

                      limpiarRregistro();

                }
            }  
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería"+ex.toString(), 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia"+ex.toString(), 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(), 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n en recurso de Base de Datos"+ex.toString(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
  
    }//GEN-LAST:event_jBtnactualizarActionPerformed

    private void jBtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtneliminarActionPerformed

        int opc;      
        try {
            opc = JOptionPane.showConfirmDialog(this, "Esta intentando eliminar"
                                            + " un registro que contiene más \n"
                                            + " vinculaciones con otros datos"
                                            + " ¿Esta seguro de continuar?" ,                    
                                      "Eliminar", JOptionPane.YES_NO_OPTION, 
                                      JOptionPane.WARNING_MESSAGE);
            if (opc == JOptionPane.YES_OPTION)
                Ctr_Maestrante.eliminar(Integer.parseInt(this.jFtfnumcarnetb.getText()));
                JOptionPane.showMessageDialog(this, "El registro del Empleado:"
                                             + this.jFtfnumcarnetb.getText() + 
                                             "\n ha sido removido", "Eliminar",
                                             JOptionPane.INFORMATION_MESSAGE);
                limpiarRregistro();
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería"+ex.toString(), 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia"+ex.toString(), 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(), 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n al intentar registrar datos "+ex.toString()
                  + ex.getSQLState(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtneliminarActionPerformed

    private void jBtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnListarActionPerformed
      
           try {
               Ctr_Maestrante.listar(jTblRusuario);
        }
         catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería"+ex.toString(), 
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia"+ex.toString(), 
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                  + "intentar utilizar \n la librería o instancia para guardar"+ex.toString(), 
                  "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                  + "el manejo de la solicitud \n al intentar registrar datos "+ex.toString()
                  + ex.getSQLState(), 
                  "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }
         
    }//GEN-LAST:event_jBtnListarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
       
        try {
            //1. Cargar la lista de Facultades
            for (String name : Ctr_Maestrante.CargarCombobox()){
                this.jCmCoordinador.addItem(name);
            }//Fin de for        
        }
        catch (ClassNotFoundException | InstantiationException | 
                     IllegalAccessException | SQLException ex){
                JOptionPane.showMessageDialog(null, "Se ha provocado una falla"
                        + "al tratar de listar los numeros de carnet de los Coordinadores\n "
                        + " registrados actualmente", "Error al cargar"
                                + "listado",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTblRusuario.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarMouseEntered
        // TODO add your handling code here:
        jBtnGuardar.setBackground(Color.white);
        jBtnGuardar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnGuardarMouseEntered

    private void jBtnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarMouseExited
        // TODO add your handling code here:
        jBtnGuardar.setBackground(new Color(0,51,90));
        jBtnGuardar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnGuardarMouseExited

    private void jBtnbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnbuscarMouseEntered
        // TODO add your handling code here:
        jBtnbuscar.setBackground(Color.white);
        jBtnbuscar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnbuscarMouseEntered

    private void jBtnbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnbuscarMouseExited
        // TODO add your handling code here:
        jBtnbuscar.setBackground(new Color(0,51,90));
        jBtnbuscar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnbuscarMouseExited

    private void jBtnactualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnactualizarMouseEntered
        // TODO add your handling code here:
        jBtnactualizar.setBackground(Color.white);
        jBtnactualizar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnactualizarMouseEntered

    private void jBtnactualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnactualizarMouseExited
        // TODO add your handling code here:
        jBtnactualizar.setBackground(new Color(0,51,90));
        jBtnactualizar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnactualizarMouseExited

    private void jBtneliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtneliminarMouseEntered
        // TODO add your handling code here:
        jBtneliminar.setBackground(Color.white);
        jBtneliminar.setForeground(Color.black);
    }//GEN-LAST:event_jBtneliminarMouseEntered

    private void jBtneliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtneliminarMouseExited
        // TODO add your handling code here:
        jBtneliminar.setBackground(new Color(0,51,90));
        jBtneliminar.setForeground(Color.white);
    }//GEN-LAST:event_jBtneliminarMouseExited

    private void jBtnListarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnListarMouseEntered
        // TODO add your handling code here:
        jBtnListar.setBackground(Color.white);
        jBtnListar.setForeground(Color.black);
    }//GEN-LAST:event_jBtnListarMouseEntered

    private void jBtnListarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnListarMouseExited
        // TODO add your handling code here:
        jBtnListar.setBackground(new Color(0,51,90));
        jBtnListar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnListarMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.black);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,51,90));
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited
     
    
        private void clearForm () {
        this.jFtfnumcarnetb.setText("");
        this.jTxtNombre.setText("");
        this.jTxtapellido.setText("");
        this.jFtfnumcarnetb.setText("");
        this.jTxtingresos.setText("");
    }
        
    public boolean validacion(){
            boolean valido = true;  
        if (jFtfnumcarnetb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "La caja de texto  Número de carnet esta vacia.",
                    "Error de validación", JOptionPane.ERROR_MESSAGE);
            return false;
        }
         return valido;
    }
        
        public void limpiarRregistro() 
        {
        this.jTxtNombre.setText("");
        this.jTxtapellido.setText("");
        this.jFtfnumcarnetb.setText("");
        this.jTxtingresos.setText("");
        this.jCmbEstado.setText("");
        this.jCmCoordinador.setSelectedIndex(0);
        this.jCmbEstado.setBackground(Color.WHITE);
        }
        
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnListar;
    private javax.swing.JButton jBtnactualizar;
    private javax.swing.JButton jBtnbuscar;
    private javax.swing.JButton jBtneliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCmCoordinador;
    private javax.swing.JTextField jCmbEstado;
    private javax.swing.JFormattedTextField jFtfnumcarnetb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRusuario;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtapellido;
    private javax.swing.JTextField jTxtingresos;
    private javax.swing.JPanel pnlPaginar;
    // End of variables declaration//GEN-END:variables

}
